/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account { 'id' : bigint, 'name' : string }
export interface Category { 'id' : bigint, 'name' : string }
export interface Summary {
  'balance' : number,
  'totalIncome' : number,
  'totalExpense' : number,
}
export interface Transaction {
  'id' : bigint,
  'transactionType' : TransactionType,
  'date' : string,
  'description' : string,
  'account' : string,
  'category' : string,
  'amount' : number,
}
export type TransactionType = { 'expense' : null } |
  { 'income' : null };
export interface _SERVICE {
  'addAccount' : ActorMethod<[string], Account>,
  'addCategory' : ActorMethod<[string], Category>,
  'addTransaction' : ActorMethod<
    [string, string, string, string, number, TransactionType],
    Transaction
  >,
  'deleteAccount' : ActorMethod<[bigint], undefined>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'getAccounts' : ActorMethod<[], Array<Account>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getSummary' : ActorMethod<[], Summary>,
  'getTransaction' : ActorMethod<[bigint], Transaction>,
  'getTransactionsByMonth' : ActorMethod<[string], Array<Transaction>>,
  'initializeDefaults' : ActorMethod<[], undefined>,
  'updateTransaction' : ActorMethod<
    [bigint, string, string, string, string, number, TransactionType],
    Transaction
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];