/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Account = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const TransactionType = IDL.Variant({
  'expense' : IDL.Null,
  'income' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : TransactionType,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'account' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Summary = IDL.Record({
  'balance' : IDL.Float64,
  'totalIncome' : IDL.Float64,
  'totalExpense' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addAccount' : IDL.Func([IDL.Text], [Account], []),
  'addCategory' : IDL.Func([IDL.Text], [Category], []),
  'addTransaction' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, TransactionType],
      [Transaction],
      [],
    ),
  'deleteAccount' : IDL.Func([IDL.Nat], [], []),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'getAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getSummary' : IDL.Func([], [Summary], ['query']),
  'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
  'getTransactionsByMonth' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'initializeDefaults' : IDL.Func([], [], []),
  'updateTransaction' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        TransactionType,
      ],
      [Transaction],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Account = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const TransactionType = IDL.Variant({
    'expense' : IDL.Null,
    'income' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : TransactionType,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'account' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Summary = IDL.Record({
    'balance' : IDL.Float64,
    'totalIncome' : IDL.Float64,
    'totalExpense' : IDL.Float64,
  });
  
  return IDL.Service({
    'addAccount' : IDL.Func([IDL.Text], [Account], []),
    'addCategory' : IDL.Func([IDL.Text], [Category], []),
    'addTransaction' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, TransactionType],
        [Transaction],
        [],
      ),
    'deleteAccount' : IDL.Func([IDL.Nat], [], []),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'getAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getSummary' : IDL.Func([], [Summary], ['query']),
    'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
    'getTransactionsByMonth' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'initializeDefaults' : IDL.Func([], [], []),
    'updateTransaction' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          TransactionType,
        ],
        [Transaction],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };